#Configuration file for accelerate multi-GPU training
#Run: accelerate config (and accept defaults for multi-GPU)
#Then run: accelerate launch scripts/02_train.py

compute_environment: LOCAL_MACHINE
distributed_type: MULTI_GPU
downcast_bf16: 'no'
gpu_ids: all
machine_rank: 0
main_training_function: main
mixed_precision: fp16
num_machines: 1
num_processes: 2
rdzv_backend: static
same_network: true
tpu_env: []
tpu_zone: ''
use_cpu: false
use_ipex: false
